### ISSUE TITLE
Driver does not handle broken connections.

### ISSUE THREAD

**Issue by fbernier** [vertica/vertica-sql-go#51]
The driver never returns `driver.ErrBadConn` anywhere in the code, causing database connection errors not to be handled.

For example, closing a user session from Vertica using `close_user_sessions('username')`, results in a forever broken database connection with `EOF` as the error to database calls. The expected behavior would be for the driver to return `driver.ErrBadConn` so that go sql would try to get a new connection after two retries.

Also, PingContext does not return an error when the database becomes inaccessible.

**Comment by huebnerr** [comment]
Thanks. Will check into this. Good catch.

Going to have to add you to the readme.  :)

Rog

On Dec 20, 2019 9:23 AM, François Bernier <notifications@github.com> wrote:

The driver never returns driver.ErrBadConn anywhere in the code, causing database connection errors not to be handled.

For example, closing a user session from Vertica using close_user_sessions('username'), results in a forever broken database connection with EOF as the error to database calls. The expected behavior would be for the driver to return driver.ErrBadConn so that go sql would try to get a new connection after two retries.

Also, PingContext does not return an error when the database becomes inaccessible.

**Comment by huebnerr** [comment]
It seems that this issue may not be fixed as multiple runs of go tests in rapid succession can fail with broken pipes during this test.
