### ISSUE TITLE
Request Cancellation

### ISSUE THREAD

**Issue by mlh758** [vertica/vertica-sql-go#72]
This driver does not honor the cancellation of a context and will leave a query running forever.

It looks like there is a cancellation message that can be sent if you open another connection (judging by the Python driver) which will close out a long running query. All operations seem to pass through `QueryContextRaw` so monitoring the context there should be sufficient.

A question I have about implementation - what does sending a cancellation do if the query is already sending rows? Will Vertica send an error message? Complete?

**Comment by huebnerr** [comment]
I've asked this of @tomwall and he gave me some great answers. I'll ask him to cover this as well. It's been in my backlog for quite a while now.

**Comment by mlh758** [comment]
Is there an IRC or some other communication channel contributors can use to discuss changes like this? A chat/email chain/gitter etc might be a better fit for a prolonged discussion than a GitHub issue. Then we could just post a summary back to this.

**Comment by huebnerr** [comment]
Interesting idea. Let me reach out to some people internally to see if there's some "process" for that. I might go ahead and just create a Discord server if that would work. @tomwall @sitingren ideas?

**Comment by mlh758** [comment]
Discord works for me.

**Comment by fbernier** [comment]
I'd be interested in knowin more about this too

**Comment by tomwall** [comment]
Some kind persistent chat would be nice but we don't have a lot of time to go start one within the next couple of weeks, there's a lot going on behind the scenes to prepare for the now-virtual BDC at the end of the month. In the meantime we are all reachable via vertica-opensrc@microfocus.com -- it's listed on the main vertica github page but could probably be more obvious in the individual projects. 

Siting added proper cancel support to vertica-python not too long ago; the key implementation details can be seen there: https://github.com/vertica/vertica-python/commit/b08be5cca20af9ec90988fd86615d3006119cb70

The cancel request happens out of band on a separate connection. When vertica receives a cancel request it will cancel the current query, if it is still running. 

Issuing a cancel increases the chances that you'll be done receiving rows soon, but it does not guarantee that the command stops immediately. Usually you will see rows continue to go by after the cancel is issued for some period of time, but it should stop eventually. Many factors contribute to this. It is up to the network to get the cancel request to vertica, and it is up to each operator in the currently executing plan to periodically check for cancels to notice that it should stop. Only after they all do can the plan be torn down and the error sent to the client. 

From the main connection's perspective, a cancel during a query looks like any other query failure -- you'll see an ErrorResponse instead of more rows, which rolls back the current operation and should usually lead to an error/exception returned by the API. It looks no different than a dbadmin doing interrupt_statement the command rolling back for semantic reasons.

**Comment by mlh758** [comment]
Yeah I saw the Python implementation and have been basing my Go implementation on that. I would send the cancel message but wasn't seeing my running query error out. I might need to use a longer running query to test with though from the sound of it.

**Comment by tomwall** [comment]
Thanks for the PR! It looks like it is on the right track, but I'm not super familiar with go as a language so I could be missing something.

Cancel testing can be tricky because it is fundamentally asynchronous. It is a bit easier with an instrumented debug build of Vertica, but we don't have that luxury here.

The Vertica execution engine will pause in response to TCP backpressure, i.e. if the client is too slow to read data, Vertica will eventually stop sending data. If the query pauses before all the data can be sent to the client due to backpressure, you can artificially widen the window where a cancel will be processed. You can probably use that to your advantage to more reliably make a cancel occur; it may require some instrumentation in the client to slow/stop the reading of result data depending on how it is implemented. 

An easy way to generate lots of result data quickly for testing purposes is a cross join of a few system tables. If you own your Vertica instance in a dev environment that's fine to do but your DBA might not appreciate lots of test queries doing that on a real system.  

You can also compare the behavior between your cancel code and a dbadmin interrupt_statement() from a different session; once Vertica decides to do a cancel (via protocol here, or via dbadmin calling the function), Vertica's behavior is basically the same.

**Comment by mlh758** [comment]
Fortunately I have a Vertica database available with a fair amount of data in it. I've got a few queries that run ~20-30 seconds. I set a context to expire after 3 seconds.

Up until now I thought my changes just weren't working because I wouldn't get an error back fro mthe driver but then I noticed my result sets were truncated (17 rows instead of a few hundred for example).

This is my debug output for those requests:
```
<select command>
Mar 24 12:54:30.409422 DEBUG connection: -> Bind: Portal='', Statement='S8255615850724701474941318', ArgC=26
Mar 24 12:54:30.409479 DEBUG connection: -> Execute: Portal='', RowLimit=0
Mar 24 12:54:30.409520 DEBUG connection: -> Flush
waiting on results
Mar 24 12:54:30.409581 DEBUG connection: <- Cmd Description: tag=SELECT, hasRewrite=false, rewrite=''
Context cancelled, bailing
Mar 24 12:54:33.391028 DEBUG connection: -> Startup (and a bunch of noise establishing the new connection)
Sending Cancel
Mar 24 12:54:33.608476 DEBUG connection: -> Cancel: TargetPID=26039618, TargetKey='565891093'
Done normally, leaving
Request cancelled
Mar 24 12:54:34.439426 DEBUG connection: <- BindComplete
Mar 24 12:54:34.439483 DEBUG connection: <- ParameterStatus: standard_conforming_strings='on'
Mar 24 12:54:34.439500 DEBUG connection: ParameterStatus: standard_conforming_strings='on'
Mar 24 12:54:34.439513 DEBUG connection: <- ParameterStatus: MARS='off'
Mar 24 12:54:34.439521 DEBUG connection: ParameterStatus: MARS='off'
Mar 24 12:54:34.439533 DEBUG connection: <- ParameterStatus: client_locale='en_US@collation=binary'
Mar 24 12:54:34.439542 DEBUG connection: ParameterStatus: client_locale='en_US@collation=binary'
Mar 24 12:54:34.550787 DEBUG connection: <- PortalSuspended
Mar 24 12:54:34.550971 DEBUG connection: -> Close: TargetType=S, TargetName='S8255615850724701474941318'
Mar 24 12:54:34.550999 DEBUG connection: -> Flush
Mar 24 12:54:34.607109 DEBUG connection: <- CloseComplete
```

It seems like it goes through the normal process and gets a portal suspended message instead of any kind of error message. PortalSuspended also seems to be how a successful query that doesn't get cancelled ends. I could indicate an error from the driver side by returning the error from the context which would at least let consumers know it didn't complete normally.

**Comment by mlh758** [comment]
Vertica itself also seems to run the query to completion and only interrupts after rows start being sent. If I have a query that returns 1 row but takes 20 seconds to execute, and I send the cancel at 3 seconds it will still take 20 seconds to complete and I seem to always get that one row.

If I have a query that take about 5 seconds and returns ~200 rows and I cancel it at 3 seconds I'll get about 5-20 of those rows after 5 seconds.

**Comment by tomwall** [comment]
The log is a little difficult to interpret because there's multiple connections going. There's many more protocol messages than I would expect (aside: we should add a thread/connection id to each log message to make it easier to interpret).

Looking closer, I think reusing newConnection may be complicating things here. I should have noticed that earlier, apologies. I looked closer at it and it is doing more than necessary to cancel -- that does everything needed to establish a real vertica session, which is overkill and may lead to strange behavior. 

You don't need to do all that for cancel. Cancel uses the client key & pid established at the main connection's startup as temporary credentials to authenticate the cancel connection. The idea is to open a socket, send the secret derived from the already-authenticated session, and then immediately disconnect. You probably want to recycle just the "establish a socket" parts of newConnection and not the rest. You can see that in action in the python version: https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/connection.py#L374

Vertica doesn't fully support portals the way postgres does; all rows are sent back in response to an Execute message. That means PortalSuspended in the extended protocol is effectively the same thing as CommandComplete in the simple protocol. If the main connection sees either, that means the query is done you've missed your opportunity for the cancel to be processed. It is not a sign of an error that should bubble up to the application.

That could either be because vertica didn't receive the cancel request at all, or because it put all the rows on the network before it could notice & react to it. I can't tell given the uncertainty above if what you observe was expected or not, but hopefully that can get you closer to some clarity.

**Comment by mlh758** [comment]
> That means PortalSuspended in the extended protocol is effectively the same thing as CommandComplete in the simple protocol.

That much I had assumed, I was seeing it for queries I didn't cancel as well which is why it seemed like I wasn't getting an error after I cancelled. The fact that the rows got cut off made me think I was cancelling but Vertica was doing a normal looking close in response.

I used the Python implementation as a reference, that's where I got the layout of the struct from and knew to open another connection. I read that `establish_socket_connection` bit as doing a full connection but if it's just "open TCP socket, send the bytes of the struct over it" that's even easier and I'll change it to do so.

I'm definitely seeing the cancel message get sent before I receive the portal close. It's more obvious on the 20 second requests, I should have posted one of those logs instead. Maybe it's as you say and establishing the full connection is causing weirdness. I'll adjust the implementation and see what happens. Thank you for following up.

**Comment by mlh758** [comment]
@tomwall that was the key! Just opening a socket and sending the message over that instead of a full session gives me an error back from Vertica immediately.

It looks like I'll need to rebase my changes off of what @huebnerr has in PR right now, the error causes a hang in the driver and I think his changes fix that. I'll verify it later today though.

**Comment by fbernier** [comment]
Just wanted to say I'm also hitting all these issues with request cancellation and hanging on errors and thanks to all of you for working on this.

**Comment by mlh758** [comment]
@fbernier I just force pushed my branch with it rebased off of huebnerr's changes. If you want to try it out it _should_ be in a working state. I've been testing it against my own application and it seems to be working sensibly.
